from convolution.convolution import convolve
from convolution.lorentz import convolve_lorentzian
from convolution.gauss import convolve_gaussian
from convolution.broadening import calculate_broadening_parameters
from convolution.tail import extend_spectrum_tail
